// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package handlers

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Error describing the failure in submitting the thread/reply
	Error string `json:"error"`
}

// Reply Reply data.
type Reply struct {
	// Board Board where the reply is to be posted (e.g., 'b').
	Board string `json:"board"`

	// Body The message of the reply.
	Body *string `json:"body,omitempty"`

	// Email Email of the poster.
	Email *string `json:"email,omitempty"`

	// Embed URL for an embedded media link (YouTube, Spotify...).
	Embed *string `json:"embed,omitempty"`

	// Files Paths of the files to attach to the reply.
	Files *[]string `json:"files,omitempty"`

	// Name Name of the poster.
	Name *string `json:"name,omitempty"`

	// Password Password used to delete or edit the reply.
	Password *string `json:"password,omitempty"`

	// Sage Replaces email with 'rabbia' and prevents bumping the thread.
	Sage *bool `json:"sage,omitempty"`

	// Spoiler Marks attached files as spoiler.
	Spoiler *bool `json:"spoiler,omitempty"`

	// Thread ID of the thread to reply to.
	Thread int `json:"thread"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	// Id ID of the submitted thread or reply
	Id int `json:"id"`
}

// Thread Thread data.
type Thread struct {
	// Board Board where the thread is to be posted (e.g., 'b').
	Board string `json:"board"`

	// Body The message of the thread.
	Body *string `json:"body,omitempty"`

	// Email Email of the poster.
	Email *string `json:"email,omitempty"`

	// Embed URL for an embedded media link (YouTube, Spotify...).
	Embed *string `json:"embed,omitempty"`

	// Files Paths of the files to attach to the thread.
	Files *[]string `json:"files,omitempty"`

	// Name Name of the poster.
	Name *string `json:"name,omitempty"`

	// Password Password used to delete or edit the thread.
	Password *string `json:"password,omitempty"`

	// Sage Replaces email with 'rabbia' and prevents bumping the thread.
	Sage *bool `json:"sage,omitempty"`

	// Spoiler Marks attached files as spoiler.
	Spoiler *bool `json:"spoiler,omitempty"`

	// Subject Subject of the thread.
	Subject *string `json:"subject,omitempty"`
}

// PostReplyJSONRequestBody defines body for PostReply for application/json ContentType.
type PostReplyJSONRequestBody = Reply

// NewThreadJSONRequestBody defines body for NewThread for application/json ContentType.
type NewThreadJSONRequestBody = Thread

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Post reply
	// (POST /reply)
	PostReply(ctx echo.Context) error
	// Create new thread
	// (POST /thread)
	NewThread(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostReply converts echo context to params.
func (w *ServerInterfaceWrapper) PostReply(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostReply(ctx)
	return err
}

// NewThread converts echo context to params.
func (w *ServerInterfaceWrapper) NewThread(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.NewThread(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/reply", wrapper.PostReply)
	router.POST(baseURL+"/thread", wrapper.NewThread)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXXW/bNhT9KxfsgLSAK8dt96K3NeuAAFsRJN6Aoc7DlXRtMZVIjqTiGoH/+8APWbHF",
	"dG6AbQm2J8v8uPfcw8OjqztWylZJQcIalt8xU9bUon/8oLXUl2SUFIbcAH3BVjXh0c2xPP5uJ0xpqUhb",
	"Tube9B2ryJSaK8ulYHmICGGs4GIFtiZYIm86TcAFmK5oubX9jK01YTXVpJoNmwzpY/gJsxvl/hqruVix",
	"7XbCNP3RcU0Vyz/FVde7ZbK4odI6sJc+4gieH4YKLWb3092xQqKuWM4KNmGFrDYsZ/OaG+AGEAStwUME",
	"KyNkWCxezEAuwW+EaTFlE7bkjSPnEzvLFwuFtl4srFws3PAsa9U7NknMvMnWVLS+CB+Z5bMR2RHdYTXv",
	"fe51TZo8mwEjNw5mQaCksVTBS8pW2QROipNXe0X7Wg/47Ys/zDSvCVoyBlfkit4l2w/47YyN0lOLvEnI",
	"yg33mX1dOktvLyhB1K+XP8NSakABfkVFFbRUcYSGi8/w8nfZzbuCJnClpOXLTZZlr5Lx4wkfxr9AW5se",
	"nl/j6kZrsawDAym+HqsTbqn1IEbw4gBqjRv3X2BLY7QfsaUjuFRozFqmdHcRZ6AzVLn6KmrIEkgNVHG7",
	"X+4orhNR+mZiSQa8AmDNbQ0nGouC4wmgqEBpunUWBkXXqn3/uJemkLIhFD6PkryhhEf9gvqziadDVTwv",
	"NBA3pKP1l/Mw2PmPPZVR5lbulL932rNdVC4srUiP3Czc8l2qlK1ddWVJxjxg2TxpHvyrqKMhu3MM+KWG",
	"kR3/NXaexjt/gLUw/igj7mGKY603u1Erdv1YT43p/iFTHfT8kKumy/8P+WiCoodP/ZmY5cjGnrtbmi5Y",
	"wCjaVZgY6/3rjV64rGOHceu4WMoEQx+u5vDDxbnXq3MtjaVvOz1Xt1SWNZdljcLl5tbftN/C6BXpW9Ju",
	"M5uwW9ImRJxlp9np64IsZjNXo1QkUHGWs7fZafaWORHY2mstNrT5HXOSSWhCGgs4dEjuPn3hJrbF3jJ9",
	"fI1uw3kVt1xGX3bMkLHvo6uUUlgSPg0q1fDS75reGJer7/fd03ealixnL6bDB8E0fg1MQ+ztPvFWd+QH",
	"wuvG1/bm9PSIpIm30nE4Dt9wHlGqiY9GbML6Zdd4amrCirQHehYQvp57yaTMN9YATlRDWxsSO00OiAc3",
	"HhU7lq5D/O5bWRp9bh1H1/4XXIKsc3GLDa8gasa/cp8QT98/FZ5+Qt4Ef3bC2rVAT4Mn76hti3rTm0eP",
	"z+LKtz0OtFt97dZOh2Y17T9nmtDSqKNAMIpKvuQl9L3ovgl9pPW8t6e/w4Ri8GfhQrGFLT2Vz9yH/vea",
	"f8lrgnqGd/4TtJvoFYNTpF1nu/0zAAD//3mmq3JoFAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
